### ISSUE TITLE
SpinnerButton

### ISSUE THREAD

**Issue by MGlolenstine** [antoyo/relm#199] opened 2020-03-01 12:34 UTC
When using the SpinnerButton, I cannot set the range, as it's method requires two arguments, which I cannot supply with the following code:

```
                    gtk::SpinButton{
                        property_climb_rate: 1.0,
                        digits: 0,
                        editable: true,
                        hexpand: true,
                        range: RANGE,
                        numeric: true,
                        value: 25565.0,
                    }
```

No matter what I set RANGE to, it doesn't work.
Tuple: One argument provided, expected two
Array: ^
if I just separate them with a comma: Identifier expected.

How can I do this?

**Comment by antoyo** [comment] 2020-03-01 13:54
Duplicate of #59.
Currently, can can either do it via the `adjustment` property, or call `set_range()` manually in `init_view()`.

**Closed by antoyo** 2020-03-01 13:54 UTC
