### ISSUE TITLE
Provide ability to set properties with multiple values

### ISSUE THREAD

**Issue by asonix** [antoyo/relm#172] opened 2019-06-09 21:35 UTC
For example, GTK's `set_wm_class` method takes two arguments, but there's currently no way to utilize this with the `view!` macro. Maybe this could be implemented by parsing tuples. into distinct arguments, like

```
gtk::ApplicationWindow {
    wmclass: ("my-app", "My App"),
}
```

If people actually need a tuple, they can do
```
gtk::ApplicationWindow {
    some_property: (("My", "Tuple")),
}
```

**Comment by antoyo** [comment] 2019-06-09 22:42
Duplicate of #59.

**Closed by antoyo** 2019-06-09 22:42 UTC
