### ISSUE TITLE
Lack of basic documentation

### ISSUE THREAD

**Issue by alexxbb** [antoyo/relm#255] opened 2021-01-06 06:24 UTC
Relm introduces some new types which are not explained at all in the docs. 
structs and traits like **Component**, **Container**, **Widget** etc could have at least a minimal explanation on what they are what they do and when and why to use them. 
For example the only place where I saw the use of Component is widgets_list.rs.

Any chance to get the docs updated with just the basics? 
Thanks!

**Comment by antoyo** [comment] 2021-01-06 12:19
For now, there's the [relm tutorial](https://relm.antoyo.xyz/documentation/tutorial/).
That does not explain everything, but it's a start.

**Comment by antoyo** [comment] 2021-02-13 17:39
Closing as it is a duplicate of #26.

**Closed by antoyo** 2021-02-13 17:39 UTC
