### ISSUE TITLE
How to treat time-lag of connect_draw?

### ISSUE THREAD

**Issue by myuon** [antoyo/relm#112] opened 2018-04-16 13:56 UTC
To build an application with `gtk::DrawingArea`, it seems to be natural to connect its `draw` signal to emit `Msg::Draw` message. Once `queue_draw` called, the callback with `connect_draw` will be called first, Draw signal will be emitted and in `update` function the drawing operations will be finally performed.

But there is a time-lag between `connect_draw` called and `update` function called.
Also, `connect_draw` will clear the canvas in GTK, this time-lag causes an annoying flash on screen.

Question: is there a way to avoid this problem? Since the function `queue_draw` will be also called by GTK internally, I might need some hacks on `connect_draw`.

**Comment by antoyo** [comment] 2018-04-16 18:11
For now, the event needs to be handled synchronously.
Duplicate of [this issue](https://github.com/antoyo/relm/issues/57).

**Closed by antoyo** 2018-04-16 18:11 UTC
