### ISSUE TITLE
view macro and property function with multiple arguments

### ISSUE THREAD

**Issue by roblabla** [antoyo/relm#71] opened 2017-10-19 09:16 UTC
Hello,

I'm currently toying around with relm, and trying to use a `scale` with the view function. The trouble is, some properties can only be set in pair, for instance the [`range` of a scale](https://docs.rs/gtk/0.2.0/gtk/trait.RangeExt.html#tymethod.set_range) is two arguments, a min and a max. There are a few other examples (alignment is usually two arguments for x/y, same with padding...).

Is there a way to pass two arguments to a property with the view macro ? Something like

```
view! {
    gtk::Scale {
        range: (0., 5.)
    }
}
```

**Comment by antoyo** [comment] 2017-10-19 12:08
This is a known issue.
Usually, there's other methods that can be used (as you can see in the following link), but I can't find the one for your case.
I usually use an [`Adjustment`](https://docs.rs/gtk/0.2.0/gtk/struct.Adjustment.html) when working with such kind of widgets, but I still can't set the values with the `view!` attribute.
So, for now, you need to call the function somewhere else, possibly in the `init_view()` method if you want to set the range at the widget creation.

Closing since it is a duplicate of #59.

**Closed by antoyo** 2017-10-19 12:08 UTC
