### ISSUE TITLE
Broken docs

### ISSUE THREAD

**Issue by luc-tielen** [antoyo/relm#73] opened 2017-10-28 15:48 UTC
docs.rs and crates.io both have weird/buggy formatting

**Comment by antoyo** [comment] 2017-10-28 15:54
For crates.io, I can't do anything.
They changed the purpose of [the issue I opened](https://github.com/rust-lang/crates.io/issues/995) and "fixed" it.

For docs.rs, can you tell me what's wrong?

**Comment by luc-tielen** [comment] 2017-10-28 15:56
It's most likely related?

https://docs.rs/relm/0.10.1/relm/fn.run.html is an example of weird formatting.

**Comment by cars10** [comment] 2017-10-28 15:57
Probably caused by the switch to markdown.

**Comment by zzeroo** [comment] 2017-11-12 16:29
@luc-tielen Do you know even more incorrect text passages?

**Comment by luc-tielen** [comment] 2017-11-12 19:16
@zzeroo just skimmed through most doc pages, also found:
- https://docs.rs/relm/0.10.1/relm/fn.init_test.html

Rest looks fine I think.

If I knew it was only a small fix I could've done them myself, or will you fix remaining?

**Comment by zzeroo** [comment] 2017-11-12 20:54
@luc-tielen I've the tools up and running so I was so free to make the PR. Thank you for your contributions.

**Comment by antoyo** [comment] 2017-11-13 13:05
That was fixed by pr #75 and #76.
Thank you.

**Closed by antoyo** 2017-11-13 13:05 UTC
