### ISSUE TITLE
allow to set widget class through the DSL

### ISSUE THREAD

**Issue by emmanueltouzery** [antoyo/relm#192] opened 2020-02-07 20:34 UTC
as far as I know currently to give a CSS style to a widget in relm, we must do:

```
    fn init_view(&mut self) {
        self.event_time_label
            .get_style_context()
            .add_class("event_time");
    }

// ...

                    #[name="event_time_label"]
                    gtk::Label {
```

It would be great if we could just do:

```
                    gtk::Label {
                          css_class: "event_time"
```

Or something of the sort.

**Comment by antoyo** [comment] 2020-02-07 20:38
Duplicate of #25.

**Closed by antoyo** 2020-02-07 20:38 UTC
